name: bhmw-alerts

on:
  schedule:
    - cron:  '0,30 * * * *'

  workflow_dispatch:

jobs:
  build_bhmw_alerts:
    runs-on: ubuntu-latest
    name: bhmw-alerts
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install requirements
        run: pip install -r requirements.txt
      - name: python script run
        run: |
          python bhmw.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
